targets:
  $default:
    builders:
      source_gen|combining_builder:
        options:
          ignore_for_file:
            - type=lint
      freezed:
        generate_for:
          include:
            - lib/model/*.dart
      json_serializable:
        generate_for:
          include:
            - lib/model/*.dart
        options:
          field_rename: snake
          checked: true
