name: yumemi_weather
description: A package that be used in yumemi-inc/flutter-training-template for getting pseudo weather forecast.
version: 1.0.0
homepage: https://yumemi-inc.github.io/flutter-training-template/

environment:
  sdk: '>=2.18.2 <4.0.0'

dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.0
