name: cleanup_template
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.3.0

dependencies:
  file: ^7.0.0
  freezed_annotation: ^2.4.1
  http: ^1.2.1
  json_annotation: ^4.8.1
  path: ^1.9.0
  pub_semver: ^2.1.4
  riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  yumemi_lints: ^1.7.0

dev_dependencies:
  build_runner: ^2.4.8
  custom_lint: ^0.6.2
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
  test: ^1.25.2
